# Generated by Django 3.2.25 on 2024-06-25 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=255)),
                ('editorial', models.CharField(max_length=100)),
                ('aniopublicacion', models.IntegerField(default=2024)),
                ('titulo', models.CharField(max_length=255)),
                ('precio', models.FloatField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='administrador/img')),
                ('stock', models.IntegerField(default=0)),
                ('idcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.categoria')),
            ],
        ),
    ]
