# Generated by Django 3.2.25 on 2024-06-25 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0002_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(default='', max_length=10)),
                ('direccion', models.CharField(default='', max_length=50)),
                ('id_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('iva', models.FloatField(default=0.0)),
                ('nrofactura', models.CharField(default='', max_length=20)),
                ('subtotal', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('idcliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='detallefactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precioTotal', models.FloatField(default=0.0)),
                ('precioUnitario', models.FloatField(default=0.0)),
                ('idfactura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.factura')),
                ('idlibro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.libro')),
            ],
        ),
    ]
